development:
  adapter: postgresql
  encoding: utf8
  database: ncp_development
  username:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: ncp_test
  username:
  host: localhost

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: ncp_production
  pool: 5
  username: sake
  password: ARprmSbqIl1eFphH
